group:
  repos: |
    trigun14/stage1@main
  files:
    - source: README.md
      dest: stage-README.md
    - source: dev-ai-gateway-values.yaml
      dest: stage-ai-gateway-values.yaml
      template:
      image:
        tag: 'new-dynamic-tag-value'
    - source: dev-api-env-values.yaml
      dest: stage-api-env-values.yaml
    - source: dev-budget-checker-values.yaml
      dest: stage-budget-checker-values.yaml
    - source: dev-bullboard-values.yaml
      dest: stage-bullboard-values.yaml
    - source: dev-catalog-automation-values.yaml
      dest: stage-catalog-automation-values.yaml
    - source: dev-common-values.yaml
      dest: stage-common-values.yaml
