name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch of the dev repository

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev1
          ref: main  # Checkout 'main' branch of dev repository

      - name: Checkout Stage Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage1
          path: stage_repo  # Place the stage repo in a separate directory
          ref: main  # Checkout 'main' branch of stage repository

      - name: Commit and Push Changes to Stage Repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Push to the main branch of the stage repository
          commit_message: "Sync changes from dev repository"
