name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch of the dev1 repository

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Dev1 Repository
      - name: Checkout Dev1 Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev1
          ref: main  # Checkout 'main' branch of dev1 repository

      # Step 2: Checkout Stage Repository as Destination
      - name: Checkout Stage Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/stage1
          ref: main  # Checkout 'main' branch of stage repository
          path: stage-repo  # Check it out to a separate directory to avoid conflicts


      # Step 4: Commit and Push Changes to Stage Repository
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: stage-repo
          force_with_lease: true
