name: Repo Sync

on: 
  push:
    branches:
      - main       # Trigger on push to main branch 
permissions:
      contents: write # This is required for actions/checkout

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main  # Sync with the main branch in the destination repo
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use your Personal Access Token
          target_repo: 'trigun14/stage1'   # Specify the destination repo path
          commit_message: "Sync changes from main"
