name: Validate Links and Sync Repo

on:
  push:
    branches:
      - main  # Trigger on push to master branch

jobs:
  validate-links:
    name: Validate Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout the code

      - name: Validate links
        uses: ad-m/report-link-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  sync:
    name: Sync Repo to Another Repository
    runs-on: ubuntu-latest
    needs: validate-links  # Ensure the validate-links job completes first
    steps:
      - uses: actions/checkout@v3  # Checkout the code

      - name: Pushes to another repository
        uses: o/github-sync-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo: 'trigun14/dev1'
          target_repo: 'trigun14/stage1'
          target_branch: 'main'
          force_push: true
