name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch of the dev1 repositor
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        repository: stage1/main
        force: true
