name: Copy Files to Stage Repo

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the 'main' branch of the dev1 repository

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Dev1 Repository (main branch)
        uses: actions/checkout@v3
        with:
          repository: trigun14/dev1
          ref: main  # Checkout 'main' branch of dev1 repository

      - name: Push Files to Stage Repository
        uses: nkoppel/push-files-to-another-repository@v1.1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN  }}
        with:
          source-files: '.'  # Sync all files from the root directory of dev1
          destination-username: 'https://github.com/trigun14/'
          destination-repository: 'stage1'
          destination-directory: '.'  # Place files in the root of the destination repo
          commit-message: "Sync changes from dev1 repository"
          commit-email: 'your-email@example.com'  # Replace with your email
